services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: user-service
    depends_on:
      - eureka-server

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: restaurant-service
    depends_on:
      - eureka-server

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: order-service
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    depends_on:
      - eureka-server
      - config-server
      - rabbitmq

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "8084:8084"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: delivery-service
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - eureka-server
      - rabbitmq

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: notification-service
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - eureka-server
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: api-gateway
    depends_on:
      - eureka-server
      - user-service
      - restaurant-service
      - order-service
      - delivery-service
      - notification-service
